=== pszufe/HIF-standard/schemas/hif_schema_v0.1.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/pszufe/HIF_validators/main/schemas/hif_schema_v0.1.0.json",
    "title": "Hypergraph Interchange Format v0.1.0",
    "type": "object",
    "properties":{
        "network-type": {
            "enum": ["undirected","directed","asc"]
        },
        "metadata": {
            "type":"object"
        },
        "incidences":{
            "type":"array",
                "items": {
                    "type":"object",
                    "properties":{
                        "edge": {
                            "type": ["string","integer"]
                        },
                        "node":{
                            "type": ["string","integer"]
                        },
                        "weight": {
                            "type":"number"
                        },
                        "direction": {
                            "enum": ["head","tail"]
                        },
                        "attrs": {
                            "type": "object"
                        },
                        "unevaluatedProperties": false
                    },
                    "required" : ["edge","node"]            
                }
        },
        "nodes": {
            "type":"array",
            "items":{
                "type":"object",
                "properties":{
                    "node":{
                        "type": ["string","integer"]
                    },
                    "weight": {
                        "type":"number"
                    },
                    "attrs": {
                        "type": "object"
                    } ,                    
                    "unevaluatedProperties": false              
                },
                "required":["node"]
            }
        },              
        "edges": {
            "type":"array",
            "items":{
                "type":"object",
                "properties":{
                    "edge":{
                        "type": ["string","integer"]
                    },
                    "weight": {
                        "type":"number"
                    },
                    "attrs": {
                        "type": "object"
                    } ,                    
                    "unevaluatedProperties": false              
                },
                "required":["edge"]
            }
        },
        "unevaluatedProperties": false
    },
    "required": ["incidences"],
    "additionalProperties": false
}

=== pszufe/HIF-standard/tutorials/data/e-coli.json
{
  "metadata": {
    "name": "e_coli_core",
    "organism": "Escherichia coli str. K-12 substr. MG1655"
  },
  "network-type": "directed",
  "nodes": [
    {
      "attr": {
        "name": "3-Phospho-D-glycerate"
      },
      "node": "3pg_c"
    },
    {
      "attr": {
        "name": "Succinate"
      },
      "node": "succ_e"
    },
    {
      "attr": {
        "name": "Ethanol"
      },
      "node": "etoh_e"
    },
    {
      "attr": {
        "name": "3-Phospho-D-glyceroyl phosphate"
      },
      "node": "13dpg_c"
    },
    {
      "attr": {
        "name": "D-Fructose 1,6-bisphosphate"
      },
      "node": "fdp_c"
    },
    {
      "attr": {
        "name": "D-Xylulose 5-phosphate"
      },
      "node": "xu5p__D_c"
    },
    {
      "attr": {
        "name": "AMP C10H12N5O7P"
      },
      "node": "amp_c"
    },
    {
      "attr": {
        "name": "Ethanol"
      },
      "node": "etoh_c"
    },
    {
      "attr": {
        "name": "D-Fructose 6-phosphate"
      },
      "node": "f6p_c"
    },
    {
      "attr": {
        "name": "Oxaloacetate"
      },
      "node": "oaa_c"
    },
    {
      "attr": {
        "name": "Nicotinamide adenine dinucleotide - reduced"
      },
      "node": "nadh_c"
    },
    {
      "attr": {
        "name": "Phosphoenolpyruvate"
      },
      "node": "pep_c"
    },
    {
      "attr": {
        "name": "Succinate"
      },
      "node": "succ_c"
    },
    {
      "attr": {
        "name": "Nicotinamide adenine dinucleotide phosphate"
      },
      "node": "nadp_c"
    },
    {
      "attr": {
        "name": "Nicotinamide adenine dinucleotide phosphate - reduced"
      },
      "node": "nadph_c"
    },
    {
      "attr": {
        "name": "Glyoxylate"
      },
      "node": "glx_c"
    },
    {
      "attr": {
        "name": "2-Oxoglutarate"
      },
      "node": "akg_c"
    },
    {
      "attr": {
        "name": "Fumarate"
      },
      "node": "fum_c"
    },
    {
      "attr": {
        "name": "Acetaldehyde"
      },
      "node": "acald_e"
    },
    {
      "attr": {
        "name": "ADP C10H12N5O10P2"
      },
      "node": "adp_c"
    },
    {
      "attr": {
        "name": "Sedoheptulose 7-phosphate"
      },
      "node": "s7p_c"
    },
    {
      "attr": {
        "name": "CO2 CO2"
      },
      "node": "co2_e"
    },
    {
      "attr": {
        "name": "Acetyl phosphate"
      },
      "node": "actp_c"
    },
    {
      "attr": {
        "name": "Acetyl-CoA"
      },
      "node": "accoa_c"
    },
    {
      "attr": {
        "name": "Citrate"
      },
      "node": "cit_c"
    },
    {
      "attr": {
        "name": "Dihydroxyacetone phosphate"
      },
      "node": "dhap_c"
    },
    {
      "attr": {
        "name": "6-Phospho-D-gluconate"
      },
      "node": "6pgc_c"
    },
    {
      "attr": {
        "name": "D-Lactate"
      },
      "node": "lac__D_e"
    },
    {
      "attr": {
        "name": "D-Erythrose 4-phosphate"
      },
      "node": "e4p_c"
    },
    {
      "attr": {
        "name": "L-Glutamine"
      },
      "node": "gln__L_c"
    },
    {
      "attr": {
        "name": "2-Oxoglutarate"
      },
      "node": "akg_e"
    },
    {
      "attr": {
        "name": "Ubiquinone-8"
      },
      "node": "q8_c"
    },
    {
      "attr": {
        "name": "Succinyl-CoA"
      },
      "node": "succoa_c"
    },
    {
      "attr": {
        "name": "D-Ribulose 5-phosphate"
      },
      "node": "ru5p__D_c"
    },
    {
      "attr": {
        "name": "Fumarate"
      },
      "node": "fum_e"
    },
    {
      "attr": {
        "name": "Ammonium"
      },
      "node": "nh4_c"
    },
    {
      "attr": {
        "name": "Coenzyme A"
      },
      "node": "coa_c"
    },
    {
      "attr": {
        "name": "Isocitrate"
      },
      "node": "icit_c"
    },
    {
      "attr": {
        "name": "H2O H2O"
      },
      "node": "h2o_c"
    },
    {
      "attr": {
        "name": "Acetate"
      },
      "node": "ac_e"
    },
    {
      "attr": {
        "name": "ATP C10H12N5O13P3"
      },
      "node": "atp_c"
    },
    {
      "attr": {
        "name": "L-Malate"
      },
      "node": "mal__L_c"
    },
    {
      "attr": {
        "name": "D-Glycerate 2-phosphate"
      },
      "node": "2pg_c"
    },
    {
      "attr": {
        "name": "H+"
      },
      "node": "h_c"
    },
    {
      "attr": {
        "name": "Alpha-D-Ribose 5-phosphate"
      },
      "node": "r5p_c"
    },
    {
      "attr": {
        "name": "D-Lactate"
      },
      "node": "lac__D_c"
    },
    {
      "attr": {
        "name": "Formate"
      },
      "node": "for_e"
    },
    {
      "attr": {
        "name": "Ammonium"
      },
      "node": "nh4_e"
    },
    {
      "attr": {
        "name": "L-Glutamine"
      },
      "node": "gln__L_e"
    },
    {
      "attr": {
        "name": "Phosphate"
      },
      "node": "pi_e"
    },
    {
      "attr": {
        "name": "Pyruvate"
      },
      "node": "pyr_e"
    },
    {
      "attr": {
        "name": "Phosphate"
      },
      "node": "pi_c"
    },
    {
      "attr": {
        "name": "D-Glucose"
      },
      "node": "glc__D_e"
    },
    {
      "attr": {
        "name": "Ubiquinol-8"
      },
      "node": "q8h2_c"
    },
    {
      "attr": {
        "name": "L-Glutamate"
      },
      "node": "glu__L_c"
    },
    {
      "attr": {
        "name": "H2O H2O"
      },
      "node": "h2o_e"
    },
    {
      "attr": {
        "name": "Acetaldehyde"
      },
      "node": "acald_c"
    },
    {
      "attr": {
        "name": "L-Malate"
      },
      "node": "mal__L_e"
    },
    {
      "attr": {
        "name": "O2 O2"
      },
      "node": "o2_e"
    },
    {
      "attr": {
        "name": "Formate"
      },
      "node": "for_c"
    },
    {
      "attr": {
        "name": "Acetate"
      },
      "node": "ac_c"
    },
    {
      "attr": {
        "name": "Nicotinamide adenine dinucleotide"
      },
      "node": "nad_c"
    },
    {
      "attr": {
        "name": "D-Fructose"
      },
      "node": "fru_e"
    },
    {
      "attr": {
        "name": "L-Glutamate"
      },
      "node": "glu__L_e"
    },
    {
      "attr": {
        "name": "CO2 CO2"
      },
      "node": "co2_c"
    },
    {
      "attr": {
        "name": "D-Glucose 6-phosphate"
      },
      "node": "g6p_c"
    },
    {
      "attr": {
        "name": "Pyruvate"
      },
      "node": "pyr_c"
    },
    {
      "attr": {
        "name": "6-phospho-D-glucono-1,5-lactone"
      },
      "node": "6pgl_c"
    },
    {
      "attr": {
        "name": "Cis-Aconitate"
      },
      "node": "acon_C_c"
    },
    {
      "attr": {
        "name": "H+"
      },
      "node": "h_e"
    },
    {
      "attr": {
        "name": "O2 O2"
      },
      "node": "o2_c"
    },
    {
      "attr": {
        "name": "Glyceraldehyde 3-phosphate"
      },
      "node": "g3p_c"
    }
  ],
  "edges": [
    {
      "attr": {
        "name": "Succinyl-CoA synthetase (ADP-forming)"
      },
      "edge": "SUCOAS_reverse"
    },
    {
      "attr": {
        "name": "H2O exchange"
      },
      "edge": "EX_h2o_e"
    },
    {
      "attr": {
        "name": "Malate transport via proton symport (2 H)"
      },
      "edge": "MALt2_2"
    },
    {
      "attr": {
        "name": "Fumarase"
      },
      "edge": "FUM"
    },
    {
      "attr": {
        "name": "H2O transport via diffusion"
      },
      "edge": "H2Ot"
    },
    {
      "attr": {
        "name": "Glucose-6-phosphate isomerase"
      },
      "edge": "PGI_reverse"
    },
    {
      "attr": {
        "name": "H+ exchange"
      },
      "edge": "EX_h_e_reverse"
    },
    {
      "attr": {
        "name": "Ribose-5-phosphate isomerase"
      },
      "edge": "RPI_reverse"
    },
    {
      "attr": {
        "name": "Phosphate reversible transport via symport"
      },
      "edge": "PIt2r"
    },
    {
      "attr": {
        "name": "Glutaminase"
      },
      "edge": "GLUN"
    },
    {
      "attr": {
        "name": "Pyruvate transport in via proton symport"
      },
      "edge": "PYRt2_reverse"
    },
    {
      "attr": {
        "name": "Phosphoglycerate mutase"
      },
      "edge": "PGM_reverse"
    },
    {
      "attr": {
        "name": "D-Glucose exchange"
      },
      "edge": "EX_glc__D_e"
    },
    {
      "attr": {
        "name": "D-Glucose exchange"
      },
      "edge": "EX_glc__D_e_reverse"
    },
    {
      "attr": {
        "name": "Transaldolase"
      },
      "edge": "TALA"
    },
    {
      "attr": {
        "name": "CO2 transporter via diffusion"
      },
      "edge": "CO2t"
    },
    {
      "attr": {
        "name": "Glutamate synthase (NADPH)"
      },
      "edge": "GLUSy"
    },
    {
      "attr": {
        "name": "Acetate kinase"
      },
      "edge": "ACKr_reverse"
    },
    {
      "attr": {
        "name": "Ammonia exchange"
      },
      "edge": "EX_nh4_e"
    },
    {
      "attr": {
        "name": "Acetate reversible transport via proton symport"
      },
      "edge": "ACt2r"
    },
    {
      "attr": {
        "name": "Phosphoglycerate kinase"
      },
      "edge": "PGK"
    },
    {
      "attr": {
        "name": "Transaldolase"
      },
      "edge": "TALA_reverse"
    },
    {
      "attr": {
        "name": "Triose-phosphate isomerase"
      },
      "edge": "TPI"
    },
    {
      "attr": {
        "name": "ATP maintenance requirement"
      },
      "edge": "ATPM"
    },
    {
      "attr": {
        "name": "Succinate transport via proton symport (2 H)"
      },
      "edge": "SUCCt2_2"
    },
    {
      "attr": {
        "name": "Fructose-bisphosphate aldolase"
      },
      "edge": "FBA_reverse"
    },
    {
      "attr": {
        "name": "Cytochrome oxidase bd (ubiquinol-8: 2 protons)"
      },
      "edge": "CYTBD"
    },
    {
      "attr": {
        "name": "D-Fructose exchange"
      },
      "edge": "EX_fru_e"
    },
    {
      "attr": {
