=== pszufe/HIF-standard/schemas/hif_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/pszufe/HIF_validators/main/schemas/schema.json",
    "title": "Hypergraph Interchange Format",
    "version": "latest",
    "type": "object",
    "properties": {
        "network-type": {
            "enum": [
                "undirected",
                "directed",
                "asc"
            ]
        },
        "metadata": {
            "type": "object"
        },
        "incidences": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "edge": {
                        "type": [
                            "string",
                            "integer"
                        ]
                    },
                    "node": {
                        "type": [
                            "string",
                            "integer"
                        ]
                    },
                    "weight": {
                        "type": "number"
                    },
                    "direction": {
                        "enum": [
                            "head",
                            "tail"
                        ]
                    },
                    "attrs": {
                        "type": "object"
                    }
                },
                "unevaluatedProperties": false,
                "additionalProperties": false,
                "required": [
                    "edge",
                    "node"
                ]
            }
        },
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "node": {
                        "type": [
                            "string",
                            "integer"
                        ]
                    },
                    "weight": {
                        "type": "number"
                    },
                    "attrs": {
                        "type": "object"
                    }
                },
                "unevaluatedProperties": false,
                "additionalProperties": false,
                "required": [
                    "node"
                ]
            }
        },
        "edges": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "edge": {
                        "type": [
                            "string",
                            "integer"
                        ]
                    },
                    "weight": {
                        "type": "number"
                    },
                    "attrs": {
                        "type": "object"
                    }
                },
                "unevaluatedProperties": false,
                "additionalProperties": false,
                "required": [
                    "edge"
                ]
            }
        }
    },
    "unevaluatedProperties": false,
    "additionalProperties": false,
    "required": [
        "incidences"
    ]
}

=== pszufe/HIF-standard/tutorials/data/publications_main_component.hif.json
{"edges": [{"edge": "A Survey on Hypergraph Mining: Patterns, Tools, and Generators", "weight": 1, "attrs": {"_level": 0, "tags": ["Social and Information Networks", "Databases", "Physics and Society"], "date": "2024-01-16", "abstract": "Hypergraphs are a natural and powerful choice for modeling group interactions in the real world, which are often referred to as higher-order networks. For example, when modeling collaboration networks, where collaborations can involve not just two but three or more people, employing hypergraphs allows us to explore beyond pairwise (dyadic) patterns and capture groupwise (polyadic) patterns. The mathematical complexity of hypergraphs offers both opportunities and challenges for learning and mining on hypergraphs, and hypergraph mining, which seeks to enhance our understanding of underlying systems through hypergraph modeling, gained increasing attention in research. Researchers have discovered various structural patterns in real-world hypergraphs, leading to the development of mining tools. Moreover, they have designed generators with the aim of reproducing and thereby shedding light on these patterns. In this survey, we provide a comprehensive overview of the current landscape of hypergraph mining, covering patterns, tools, and generators. We provide comprehensive taxonomies for them, and we also provide in-depth discussions to provide insights into future research on hypergraph mining.", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "Hyper-YOLO: When Visual Object Detection Meets Hypergraph Computation", "weight": 1, "attrs": {"_level": 0, "tags": ["Computer Vision and Pattern Recognition"], "date": "2024-08-08", "abstract": "We introduce Hyper-YOLO, a new object detection method that integrates hypergraph computations to capture the complex high-order correlations among visual features. Traditional YOLO models, while powerful, have limitations in their neck designs that restrict the integration of cross-level features and the exploitation of high-order feature interrelationships. To address these challenges, we propose the Hypergraph Computation Empowered Semantic Collecting and Scattering (HGC-SCS) framework, which transposes visual feature maps into a semantic space and constructs a hypergraph for high-order message propagation. This enables the model to acquire both semantic and structural information, advancing beyond conventional feature-focused learning. Hyper-YOLO incorporates the proposed Mixed Aggregation Network (MANet) in its backbone for enhanced feature extraction and introduces the Hypergraph-Based Cross-Level and Cross-Position Representation Network (HyperC2Net) in its neck. HyperC2Net operates across five scales and breaks free from traditional grid structures, allowing for sophisticated high-order interactions across levels and positions. This synergy of components positions Hyper-YOLO as a state-of-the-art architecture in various scale models, as evidenced by its superior performance on the COCO dataset. Specifically, Hyper-YOLO-N significantly outperforms the advanced YOLOv8-N and YOLOv9-T with 12\\% $\\text{AP}^{val}$ and 9\\% $\\text{AP}^{val}$ improvements. The source codes are at ttps://github.com/iMoonLab/Hyper-YOLO.", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "HyperSMOTE: A Hypergraph-based Oversampling Approach for Imbalanced Node Classifications", "weight": 1, "attrs": {"_level": 0, "tags": ["Machine Learning", "Artificial Intelligence"], "date": "2024-09-09", "abstract": "Hypergraphs are increasingly utilized in both unimodal and multimodal data scenarios due to their superior ability to model and extract higher-order relationships among nodes, compared to traditional graphs. However, current hypergraph models are encountering challenges related to imbalanced data, as this imbalance can lead to biases in the model towards the more prevalent classes. While the existing techniques, such as GraphSMOTE, have improved classification accuracy for minority samples in graph data, they still fall short when addressing the unique structure of hypergraphs. Inspired by SMOTE concept, we propose HyperSMOTE as a solution to alleviate the class imbalance issue in hypergraph learning. This method involves a two-step process: initially synthesizing minority class nodes, followed by the nodes integration into the original hypergraph. We synthesize new nodes based on samples from minority classes and their neighbors. At the same time, in order to solve the problem on integrating the new node into the hypergraph, we train a decoder based on the original hypergraph incidence matrix to adaptively associate the augmented node to hyperedges. We conduct extensive evaluation on multiple single-modality datasets, such as Cora, Cora-CA and Citeseer, as well as multimodal conversation dataset MELD to verify the effectiveness of HyperSMOTE, showing an average performance gain of 3.38% and 2.97% on accuracy, respectively.", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "LightHGNN: Distilling Hypergraph Neural Networks into MLPs for $100\\times$ Faster Inference", "weight": 1, "attrs": {"_level": 0, "tags": ["Machine Learning"], "date": "2024-02-06", "abstract": "Hypergraph Neural Networks (HGNNs) have recently attracted much attention and exhibited satisfactory performance due to their superiority in high-order correlation modeling. However, it is noticed that the high-order modeling capability of hypergraph also brings increased computation complexity, which hinders its practical industrial deployment. In practice, we find that one key barrier to the efficient deployment of HGNNs is the high-order structural dependencies during inference. In this paper, we propose to bridge the gap between the HGNNs and inference-efficient Multi-Layer Perceptron (MLPs) to eliminate the hypergraph dependency of HGNNs and thus reduce computational complexity as well as improve inference speed. Specifically, we introduce LightHGNN and LightHGNN$^+$ for fast inference with low complexity. LightHGNN directly distills the knowledge from teacher HGNNs to student MLPs via soft labels, and LightHGNN$^+$ further explicitly injects reliable high-order correlations into the student MLPs to achieve topology-aware distillation and resistance to over-smoothing. Experiments on eight hypergraph datasets demonstrate that even without hypergraph dependency, the proposed LightHGNNs can still achieve competitive or even better performance than HGNNs and outperform vanilla MLPs by $16.3$ on average. Extensive experiments on three graph datasets further show the average best performance of our LightHGNNs compared with all other methods. Experiments on synthetic hypergraphs with 5.5w vertices indicate LightHGNNs can run $100\\times$ faster than HGNNs, showcasing their ability for latency-sensitive deployments.", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "Hyper-3DG: Text-to-3D Gaussian Generation via Hypergraph", "weight": 1, "attrs": {"_level": 0, "tags": ["Computer Vision and Pattern Recognition"], "date": "2024-03-14", "abstract": "Text-to-3D generation represents an exciting field that has seen rapid advancements, facilitating the transformation of textual descriptions into detailed 3D models. However, current progress often neglects the intricate high-order correlation of geometry and texture within 3D objects, leading to challenges such as over-smoothness, over-saturation and the Janus problem. In this work, we propose a method named ``3D Gaussian Generation via Hypergraph (Hyper-3DG)'', designed to capture the sophisticated high-order correlations present within 3D objects. Our framework is anchored by a well-established mainflow and an essential module, named ``Geometry and Texture Hypergraph Refiner (HGRefiner)''. This module not only refines the representation of 3D Gaussians but also accelerates the update process of these 3D Gaussians by conducting the Patch-3DGS Hypergraph Learning on both explicit attributes and latent visual features. Our framework allows for the production of finely generated 3D objects within a cohesive optimization, effectively circumventing degradation. Extensive experimentation has shown that our proposed method significantly enhances the quality of 3D generation while incurring no additional computational overhead for the underlying framework. (Project code: https://github.com/yjhboy/Hyper3DG)", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "Assigning Entities to Teams as a Hypergraph Discovery Problem", "weight": 1, "attrs": {"_level": 0, "tags": ["Social and Information Networks", "Spectral Theory", "Physics and Society"], "date": "2024-03-06", "abstract": "We propose a team assignment algorithm based on a hypergraph approach focusing on resilience and diffusion optimization. Specifically, our method is based on optimizing the algebraic connectivity of the Laplacian matrix of an edge-dependent vertex-weighted hypergraph. We used constrained simulated annealing, where we constrained the effort agents can exert to perform a task and the minimum effort a task requires to be completed. We evaluated our methods in terms of the number of unsuccessful patches to drive our solution into the feasible region and the cost of patching. We showed that our formulation provides more robust solutions than the original data and the greedy approach. We hope that our methods motivate further research in applying hypergraphs to similar problems in different research areas and in exploring variations of our methods.", "funding_agencies": [], "source": "Arxiv"}}, {"edge": "Hypergraph based Understanding for Document Semantic Entity Recognition", "weight": 1, "attrs": {"_level": 0, "tags": ["Artificial Intelligence"], "date": "2024-07-09", "abstract": "Semantic entity recognition is an important task in the field of visually-rich document understanding. It distinguishes the semantic types of text by analyzing the position relationship between text node
